### ISSUE TITLE
429: too many API requests

### ISSUE THREAD

**Issue by rgerbranda** [Emilv2/pydelijn#1]
My Home Assistant log is filled with errors.

```
2023-06-03 12:23:32.843 ERROR (MainThread) [homeassistant.components.delijn.sensor] De Lijn http error
2023-06-03 12:32:32.856 ERROR (MainThread) [homeassistant.components.delijn.sensor] De Lijn http error
```
When I dive into the code, I think this is caused by error 429.

Is it possible to reduce the number of requests to api.delijn.be ?

```
Endpoint URL: https://api.delijn.be/DLKernOpenData/api/v1/kleuren/

text: { "statusCode": 429, "message": "Rate limit is exceeded. Try again in 1 seconds." }
Traceback (most recent call last):
  File "/usr/lib/python3.10/idlelib/run.py", line 578, in runcode
    exec(code, self.locals)
  File "/home/remko/lijn.py", line 55, in <module>
    LOOP.run_until_complete(test_pydelijn())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/remko/lijn.py", line 18, in test_pydelijn
    await delijndata.get_passages()
  File "/home/remko/.local/lib/python3.10/site-packages/pydelijn/api.py", line 112, in get_passages
    colourshex = await self.get_colourshex(common)
  File "/home/remko/.local/lib/python3.10/site-packages/pydelijn/api.py", line 72, in get_colourshex
    resultcolours = await common.api_call(endpointcolours)
  File "/home/remko/.local/lib/python3.10/site-packages/pydelijn/common.py", line 53, in api_call
    raise HttpException(message, await response.text(), response.status) #REMKO
pydelijn.common.HttpException: 429: too many API requests
```

**Comment by rgerbranda** [comment]
I have created an issue at data.delijn.be as it seems a problem at their side.
https://data.delijn.be/issues/647dc2b86e0271248882bd9f

I found a related issue in Home Assistant: https://github.com/home-assistant/core/issues/82507
